import type { RawExercise } from '../exercises';

/**
 * Minimal exercise catalog used by tests. Each entry exercises a
 * different muscle group mapping branch in normalize() so that the
 * classifier stays covered.
 */
export const fixtureExercises: RawExercise[] = [
  {
    id: 'Barbell_Bench_Press_-_Medium_Grip',
    name: 'Barbell Bench Press - Medium Grip',
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
    equipment: 'barbell',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    instructions: ['Lie on the bench.', 'Lower the bar.', 'Press it back up.'],
    category: 'strength',
    images: ['Barbell_Bench_Press_-_Medium_Grip/0.jpg', 'Barbell_Bench_Press_-_Medium_Grip/1.jpg'],
  },
  {
    id: 'Pullups',
    name: 'Pullups',
    force: 'pull',
    level: 'beginner',
    mechanic: 'compound',
    equipment: 'body only',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'middle back'],
    instructions: ['Hang from the bar.', 'Pull yourself up.'],
    category: 'strength',
    images: ['Pullups/0.jpg'],
  },
  {
    id: 'Barbell_Squat',
    name: 'Barbell Squat',
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
    equipment: 'barbell',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    instructions: ['Step under the bar.', 'Squat down.', 'Stand back up.'],
    category: 'strength',
    images: ['Barbell_Squat/0.jpg'],
  },
  {
    id: 'Plank',
    name: 'Plank',
    force: 'static',
    level: 'beginner',
    mechanic: 'isolation',
    equipment: 'body only',
    primaryMuscles: ['abdominals'],
    secondaryMuscles: [],
    instructions: ['Hold a plank position.'],
    category: 'strength',
    images: [],
  },
  {
    id: 'Treadmill_Running',
    name: 'Treadmill Running',
    force: null,
    level: 'beginner',
    mechanic: null,
    equipment: 'machine',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['calves'],
    instructions: ['Run on the treadmill.'],
    category: 'cardio',
    images: [],
  },
  {
    id: 'Barbell_Hip_Thrust',
    name: 'Barbell Hip Thrust',
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
    equipment: 'barbell',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    instructions: ['Thrust up.'],
    category: 'strength',
    images: [],
  },
];
